[package]
authors = ["ololoshka2871"]
edition = "2018"
readme = "README.md"
name = "stm32-usb-self-writer"
version = "0.1.0"

[dependencies]
embedded-hal = "0.2.4"
cortex-m = "0.7.3"
cortex-m-rt = "0.6.11" # need by stm32l4 == 0.13.0
freertos-rust = { git = "https://github.com/lobaro/FreeRTOS-rust.git", rev = "e365ca8a116cc1bd7f1667198f0cb1faaaa6d887" }

stm32l4xx-hal = { version= "0.6.0", features = ["stm32l4x2", "rt"] }

usb-device = "0.2.5"
stm32-usbd = "0.6.0"
usbd-serial = "0.1"
usbd_scsi = { path = "lib/stm32-usb.rs.saved_copy/firmware/usbd_scsi" }
usbd_mass_storage = "0.1.0"

# defmt
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2", features = ["print-defmt"] }

heatshrink-rust = { git = "https://github.com/ololoshka2871/heatshrink.rs.git", rev = "0af9332" }
emfat-rust = { path = "lib/emfat" }

[build-dependencies]
freertos-cargo-build = "0.1.1"

[profile.dev]
opt-level = 1
lto = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations

[features]
default = [
  "defmt-default",
]

 # do NOT modify these features
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []
