name: Build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: rust-stm32-r194
    steps:
      - name: Install SCTB Elpa certificate
        uses: https://gitea.sctbelpa/Public/git-action-ca-certificate-import@v2
        with:
          certificate: ${{ vars.SCTB_ROOT_CERT }}
          certificate-name: "sctb.crt"

      - name: Clone
        uses: https://gitea.sctbelpa/Public/checkout@v4
        with:
          submodules: recursive

      - name: install crates.io mirror
        run: |
          mkdir -p .cargo/
          echo '${{ vars.CARGO_MIRROR_DEFINE }}' >> .cargo/config.toml
          cat .cargo/config.toml

      - name: Build 24MHz xtal version
        run: |
          cargo build --release --features "xtal-24mhz" --bin self-writer
          arm-none-eabi-objcopy -O binary target/thumbv7em-none-eabihf/release/self-writer self-writer-24mhz.bin

      - name: Build 12MHz xtal version
        run: |
          cargo build --release --features "xtal-12mhz" --bin self-writer
          arm-none-eabi-objcopy -O binary target/thumbv7em-none-eabihf/release/self-writer self-writer-12mhz.bin

      - name: Build no-flash version
        run: |
          cargo build --release --features "xtal-24mhz,no-flash" --bin self-writer
          arm-none-eabi-objcopy -O binary target/thumbv7em-none-eabihf/release/self-writer self-writer-24mhz-no-flash.bin

      - name: Read version from Cargo.toml
        uses: https://gitea.sctbelpa/Public/toml-action@v1.2.0
        id: read_version
        with:
          file: "Cargo.toml"
          field: "package.version"

      - name: Create release
        uses: https://gitea.sctbelpa/Public/gitea-release-action@v1
        env:
          NODE_USE_SYSTEM_CA: 1
        with:
          name: v${{ steps.read_version.outputs.value }}
          body: |
            This is an automatic ${{ steps.read_version.outputs.value }} release!
          prerelease: true
          files: |
            self-writer-24mhz.bin
            self-writer-12mhz.bin
            self-writer-24mhz-no-flash.bin
