name: Build

on:
  push:
    tags:
      - v*

# Caching proxy
env:
  NODE_TLS_REJECT_UNAUTHORIZED: 0

jobs:
  build:
    runs-on: rust-stm32-r194
    steps:
      - name: Install SCTB Elpa certificate
        uses: https://gitea.sctbelpa/Public/git-action-ca-certificate-import@v2
        with:
          certificate: ${{ vars.SCTB_ROOT_CERT }}
          certificate-name: "sctb.crt"

      - name: Clone
        uses: https://gitea.sctbelpa/Public/checkout@v4
        with:
          submodules: recursive

      - name: install crates.io mirror
        run: |
          mkdir -p .cargo/
          echo '${{ vars.CARGO_MIRROR_DEFINE }}' >> .cargo/config.toml
          cat .cargo/config.toml

      - name: Build
        run: cargo build --release

      - name: Create binary dist
        run: arm-none-eabi-objcopy -O binary target/thumbv7em-none-eabihf/release/self-writer self-writer.bin

      - name: Read version from Cargo.toml
        uses: https://gitea.sctbelpa/Public/toml-action@v1.2.0
        id: read_version
        with:
          file: "Cargo.toml"
          field: "package.version"

      - name: Create release
        uses: https://gitea.sctbelpa/Public/gitea-release-action@v1
        with:
          name: v${{ steps.read_version.outputs.value }}
          body: |
            This is an automatic ${{ steps.read_version.outputs.value }} release!
          prerelease: true
          files: |
            self-writer.bin
