name: Pull Request Workflow
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - "*/*"

jobs:
  build:
    runs-on: rust-stm32-r194
    steps:
      - name: Install SCTB Elpa certificate
        uses: https://gitea.sctbelpa/Public/git-action-ca-certificate-import@v2
        with:
          certificate: ${{ vars.SCTB_ROOT_CERT }}
          certificate-name: "sctb.crt"

      - name: Clone
        uses: https://gitea.sctbelpa/Public/checkout@v4
        with:
          submodules: recursive

      - name: install crates.io mirror
        run: |
          mkdir -p .cargo/
          echo '${{ vars.CARGO_MIRROR_DEFINE }}' >> .cargo/config.toml
          cat .cargo/config.toml

      - name: Build RTC calibration test
        run: |
          cargo build --release --features "xtal-12mhz,force-defmt-logs" --bin int_rtc_test

      - name: Build 24MHz xtal version
        run: |
          cargo build --release --features "xtal-24mhz" --bin self-writer

      - name: Build 12MHz xtal version
        run: |
          cargo build --release --features "xtal-12mhz" --bin self-writer

      - name: Build no-flash version
        run: |
          cargo build --release --features "xtal-24mhz,no-flash" --bin self-writer